version: '3.8'

services:
  frontend-react:
    # Tự đặt tên image
    image: ev-charging-frontend:latest
    container_name: ev_frontend
    build:
      context: . # (Hoặc ./frontend nếu là monorepo)
      dockerfile: Dockerfile
      args:
        # Pass env vars vào build stage (Vite cần chúng khi build)
        VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "5173:80" # Map cổng 5173 của host vào cổng 80 của container (nginx default port)
    restart: always